
version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t react-app:latest ./frontend
      - docker tag react-app:latest 099199746132.dkr.ecr.us-east-1.amazonaws.com/react-app:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 099199746132.dkr.ecr.us-east-1.amazonaws.com/react-app:latest
      -  printf '[{"name":"reactapp","imageUri":"%s"}]' "099199746132.dkr.ecr.us-east-1.amazonaws.com/react-app:latest" > imagedefinitions.json
 
artifacts:
  files:
    - imagedefinitions.json
