version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    FRONTEND_IMAGE_NAME: "react-app"
    BACKEND_IMAGE_NAME: "backend-app"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 099199746132.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Pre-build complete.

  build:
    commands:
      - echo Building frontend image...
      - docker build -t $FRONTEND_IMAGE_NAME:$IMAGE_TAG ./frontend
      - docker tag $FRONTEND_IMAGE_NAME:$IMAGE_TAG 099199746132.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_IMAGE_NAME:$IMAGE_TAG

      - echo Building backend image...
      - docker build -t $BACKEND_IMAGE_NAME:$IMAGE_TAG ./backend
      - docker tag $BACKEND_IMAGE_NAME:$IMAGE_TAG 099199746132.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_IMAGE_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing frontend image...
      - docker push 099199746132.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_IMAGE_NAME:$IMAGE_TAG

      - echo Pushing backend image...
      - docker push 099199746132.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_IMAGE_NAME:$IMAGE_TAG

      - echo Writing imagedefinitions.json for ECS...
      - printf '[{"name":"reactapp","imageUri":"099199746132.dkr.ecr.%s.amazonaws.com/%s:%s"},{"name":"node-backend","imageUri":"099199746132.dkr.ecr.%s.amazonaws.com/%s:%s"}]' "$AWS_REGION" "$FRONTEND_IMAGE_NAME" "$IMAGE_TAG" "$AWS_REGION" "$BACKEND_IMAGE_NAME" "$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
