version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t backend-app:latest ./backend
      - docker tag backend-app:latest 099199746132.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest


  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 099199746132.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
      - printf '[{"name":"node-backend","imageUri":"099199746132.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
